### ISSUE TITLE
how to upload the file to direct another server using curl 

### ISSUE THREAD

**Issue by Jaydeep-01** [Onihani/filepond-php-server-example#1]
Hello, 

I like the way you implement this in the core php, but I would like to know that can we upload the files directly to another server using curl without even storing the files temporary in our server. I tried to implement the curl code right after this code just to check whether can I upload the files using curl or not.
https://github.com/Onihani/filepond-php-server-example/blob/5b8ec9cf6e42c17056d1ea301422ba1341dbcf45/util/uploadmedia.php#L20

we would glad if you can share the example with curl in the special reference of directly to another server using curl without even storing the files temporary in our server.

note: we don't have any access of another server except the curl of sending the data

**Comment by onihani** [comment]
Hello @Jaydeep-01, yes you can store the files anywhere directly without storing it temporarily. 
With uploading to another server via curl check out this post on stack overflow [uploading files with curl](https://stackoverflow.com/questions/15200632/how-to-upload-file-using-curl-with-php).

That should help upload the file to the other server

**Comment by Jaydeep-01** [comment]
Thanks for replay,

I modified some of yours and some of my code and it works 🎉

**Comment by Jaydeep-01** [comment]
I see the bug around, when I upload multiple files at the time only two files got complete upload with 200 return code and another two files are get uploaded with error code and the rest files are not get uploaded. 

![image](https://user-images.githubusercontent.com/56955505/133798927-63cf51b4-082b-43e3-824e-7b91afac532b.png)

If you have any solution then please provide here of update the project.

As far as I think the only solution can be for many files is making something sync of the code, synchronization can be the only way when we have a big and multiple files. any way please provide your thought and updates.

**Comment by onihani** [comment]
Hello @Jaydeep-01 ,
From the console logs, I think there is an error on [process.php](https://github.com/Onihani/filepond-php-server-example/blob/5b8ec9cf6e42c17056d1ea301422ba1341dbcf45/process.php#L58) line 58

On line 58, it seems we are using `array_push` to add an item to variable which is not an array (in these case the variable is null)
Hence the error

While implementing this filepond server i used a JSON file to as database to store uploaded files (references to uploaded files)

I guess in your case you can uses a real database or modify the [`readJsonFile`](https://github.com/Onihani/filepond-php-server-example/blob/5b8ec9cf6e42c17056d1ea301422ba1341dbcf45/util/read_write_functions.php#L3) function in util folder so it returns an array for storing file references instead of null

**Comment by Jaydeep-01** [comment]
Actually, for this testing purpose I used your code without making a single change in any of the file. can you make sure uploading more files at a same time works fine in your system.

**Comment by Jaydeep-01** [comment]
You mean it works fine on your system when you upload multiple (more then 5) files at a time?

**Comment by onihani** [comment]
> You mean it works fine on your system when you upload multiple (more then 5) files at a time?

Sorry for the late response.
I am not sure uploading multiple files works on my implementation but i would try ans update the code make multiple uploads work as well

**Comment by Jaydeep-01** [comment]
Sure you can try and update it because multiple files doesn't work 😊

**Comment by onihani** [comment]
@Jaydeep-01 multiple uploads works now you can update your local code with the latest changes and test
or preview the update [here](http://www.ics-courses.co.uk/natbongo/filepond-php-server-example/)

**Comment by Jaydeep-01** [comment]
@Onihani thanks for this implementation, it works fine now
